server {
    listen 80;
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige todas las rutas al index.html (necesario para el router de Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Sin cache para index.html (para que siempre cargue la versión nueva)
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
